pub const BASES: &str = [
	"Wooden Club",
	"Smithing Hammer",
	"Slim Mace",
	"Spiked Club",
	"Warpick",
	"Plated Mace",
	"Brigand Mace",
	"Construct Hammer",
	"Advanced Smithing Hammer",
	"Advanced Slim Mace",
	"Advanced Warpick",
	"Advanced Plated Mace",
	"Advanced Brigand Mace",
	"Advanced Construct Hammer",
	"Expert Slim Mace",
	"Expert Plated Mace",
	"Expert Brigand Mace",
	"Expert Smithing Hammer",
	"Expert Warpick",
	"Expert Construct Hammer",
	"Felled Greatclub",
	"Oak Greathammer",
	"Forge Maul",
	"Studded Greatclub",
	"Cultist Greathammer",
	"Temple Maul",
	"Leaden Greathammer",
	"Crumbling Maul",
	"Advanced Oak Greathammer",
	"Advanced Forge Maul",
	"Advanced Cultist Greathammer",
	"Advanced Temple Maul",
	"Advanced Leaden Greathammer",
	"Advanced Crumbling Maul",
	"Expert Forge Maul",
	"Expert Temple Maul",
	"Expert Leaden Greathammer",
	"Expert Oak Greathammer",
	"Expert Cultist Greathammer",
	"Expert Crumbling Maul",
	"Long Quarterstaff",
	"Wrapped Quarterstaff",
	"Gothic Quarterstaff",
	"Crackling Quarterstaff",
	"Crescent Quarterstaff",
	"Steelpoint Quarterstaff",
	"Slicing Quarterstaff",
	"Barrier Quarterstaff",
	"Advanced Long Quarterstaff",
	"Advanced Gothic Quarterstaff",
	"Advanced Crackling Quarterstaff",
	"Advanced Crescent Quarterstaff",
	"Advanced Slicing Quarterstaff",
	"Advanced Barrier Quarterstaff",
	"Expert Gothic Quarterstaff",
	"Expert Crescent Quarterstaff",
	"Expert Long Quarterstaff",
	"Expert Slicing Quarterstaff",
	"Expert Crackling Quarterstaff",
	"Expert Barrier Quarterstaff",
	"Crude Bow",
	"Shortbow",
	"Warden Bow",
	"Recurve Bow",
	"Composite Bow",
	"Dualstring Bow",
	"Cultist Bow",
	"Zealot Bow",
	"Advanced Shortbow",
	"Advanced Warden Bow",
	"Advanced Composite Bow",
	"Advanced Dualstring Bow",
	"Advanced Cultist Bow",
	"Advanced Zealot Bow",
	"Expert Shortbow",
	"Expert Composite Bow",
	"Expert Warden Bow",
	"Expert Zealot Bow",
	"Expert Dualstring Bow",
	"Expert Cultist Bow",
	"Makeshift Crossbow",
	"Tense Crossbow",
	"Sturdy Crossbow",
	"Varnished Crossbow",
	"Dyad Crossbow",
	"Alloy Crossbow",
	"Bombard Crossbow",
	"Construct Crossbow",
	"Advanced Tense Crossbow",
	"Advanced Sturdy Crossbow",
	"Advanced Varnished Crossbow",
	"Advanced Dyad Crossbow",
	"Advanced Bombard Crossbow",
	"Advanced Forlorn Crossbow",
	"Expert Sturdy Crossbow",
	"Expert Varnished Crossbow",
	"Expert Forlorn Crossbow",
	"Expert Tense Crossbow",
	"Expert Dyad Crossbow",
	"Expert Bombard Crossbow",
];